[build]
publish = "./exampleSite/public/"
command = "cd exampleSite && hugo --gc --minify"
[build.environment]
HUGO_VERSION = "0.128.0"
HUGO_ENV = "production"
GO_VERSION = "1.23"
NODE_ENV = "development"
